// <auto-generated />
namespace AssetTrackingSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class organization_code_introduced : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(organization_code_introduced));
        
        string IMigrationMetadata.Id
        {
            get { return "201610081507241_organization_code_introduced"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
